### ISSUE TITLE
Integrate Appveyor (Windows Continuous Integration)

### ISSUE THREAD

**Issue by luzpaz** [andreas-vox/ScribusCTL#9]
# Postponed
- Appveyor has no Qt library support for msvc2012 (see [link](https://www.appveyor.com/docs/installed-software/#qt))
- Won't support testing on XP
## Background

Continuous Integration (CI) allows to trigger a build whenever a Pull Request (PR) is made to Scribus trunk. It has the potential to help the Scribus developers. Currently there is a working CI for Linux and one in process for OSX (see https://github.com/andreas-vox/ScribusCTL/issues/2)
For Windows there is a 3rd party service that integrates in to Github called [AppVeyor](http://www.appveyor.com). 
## TODO
- [x] Consult with the only person in the universe that can install bleeding edge Scribus on Windows (jghali) 
- [x] Appveyor's [Installed software and libraries](http://www.appveyor.com/docs/installed-software)
- [x] Up to date instructions for [Building Scribus with msvc](https://github.com/scribusproject/scribus/blob/master/BUILDING_win32_msvc.txt)
- [x] Find dependencies
  - [x] Qt libs supported by appveyor
  - [x] Rest of Scribus deps are on [SF](http://sourceforge.net/projects/scribus/files/scribus-libs/)
- [ ] Build an appveyor.yml file 
### Useful references
- http://www.appveyor.com/docs/environment-variables

**Comment by luzpaz** [comment]
CC @QuLogic

**Comment by luzpaz** [comment]
Posted to [g+](https://plus.google.com/b/109612024486187515483/109612024486187515483/posts/DV8thtzeGvu)

**Comment by luzpaz** [comment]
CC @ebraminio

**Comment by ebraminio** [comment]
I like to help as I had successful attempt [here](https://github.com/khaledhosny/ots/pull/67) but I had also a yet unsuccessful attempt [here](https://github.com/behdad/harfbuzz/pull/112) (specially look at the last comment). Installing requirement, specially introducing win32 api to linker still seems magic to me (even the fact that will going to work somehow on a real installation) and someone should give me a hand on that area!

**Comment by luzpaz** [comment]
@ebraminio Thanks for the feedback! jghali on `#Scribus` Freenode says he will take a look at this next week when he has time.

**Comment by luzpaz** [comment]
Problem: There is no Qt library support for msvc2012. :-1:  

>   jghali: so currently I do not see any compelling reason to move to msvc 2013
>   jghali: when i'll upgrade it will be most likely to msvc 2015

**Comment by luzpaz** [comment]
Just learned the user "at"FeodorFitsner is the dev at appveyor
